/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhispersRouteImport } from './routes/whispers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LocationRouteImport } from './routes/location'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const WhispersRoute = WhispersRouteImport.update({
  id: '/whispers',
  path: '/whispers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/moments': typeof MomentsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/whispers': typeof WhispersRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/moments': typeof MomentsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/whispers': typeof WhispersRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/groups': typeof GroupsRoute
  '/location': typeof LocationRoute
  '/messages': typeof MessagesRoute
  '/moments': typeof MomentsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/whispers': typeof WhispersRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/groups'
    | '/location'
    | '/messages'
    | '/moments'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/search'
    | '/whispers'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/groups'
    | '/location'
    | '/messages'
    | '/moments'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/search'
    | '/whispers'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookmarks'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/groups'
    | '/location'
    | '/messages'
    | '/moments'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/search'
    | '/whispers'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  CalendarRoute: typeof CalendarRoute
  EventsRoute: typeof EventsRoute
  FeedRoute: typeof FeedRoute
  GroupsRoute: typeof GroupsRoute
  LocationRoute: typeof LocationRoute
  MessagesRoute: typeof MessagesRoute
  MomentsRoute: typeof MomentsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  WhispersRoute: typeof WhispersRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whispers': {
      id: '/whispers'
      path: '/whispers'
      fullPath: '/whispers'
      preLoaderRoute: typeof WhispersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  CalendarRoute: CalendarRoute,
  EventsRoute: EventsRoute,
  FeedRoute: FeedRoute,
  GroupsRoute: GroupsRoute,
  LocationRoute: LocationRoute,
  MessagesRoute: MessagesRoute,
  MomentsRoute: MomentsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  WhispersRoute: WhispersRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
